config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resource :random_banners, only: [:show]
      resources :banners, only: [] do
        get :image, on: :member
        get :url, on: :member
      end
    end
  end

  scope module: :web do
    root to: "welcome#index"
    resources :banners, only: [:index, :new, :create, :edit, :update, :destroy]
  end
end

app/models/banner.rb
# == Schema Information
#
# Table name: banners
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  url         :string(255)
#  image       :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  show_count  :integer          default(0)
#  click_count :integer          default(0)
#

class Banner < ActiveRecord::Base

  mount_uploader :image, BannerImageUploader
  
  validates :title, presence: true
  validates :url, presence: true

  include BannerRepository

  def conversion
    click_count.to_f / show_count.to_f
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ApplicationController
  respond_to :json
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < Api::ApplicationController
end

app/controllers/api/v1/banners_controller.rb
class Api::V1::BannersController < Api::V1::ApplicationController

  def image
    @banner = Banner.find(params[:id])
    @banner.show_count += 1
    @banner.save

    send_file @banner.image.path, disposition: "inline"
  end

  def url
    @banner = Banner.find(params[:id])
    @banner.click_count += 1
    @banner.save

    redirect_to @banner.url, status: :found
  end
end

app/controllers/api/v1/random_banners_controller.rb
class Api::V1::RandomBannersController < Api::V1::ApplicationController
  def show
    offset = rand(Banner.count)
    @banner = Banner.offset(offset).first

    render json: @banner, callback: params[:callback], serializer: Api::V1::RandomBannerSerializer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/web/application_controller.rb
class Web::ApplicationController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_gon_variables

  private

  def set_gon_variables
    gon.faye_url = configus.faye_url
  end
end

app/controllers/web/banners_controller.rb
class Web::BannersController < Web::ApplicationController
  def index
    @banners = Banner.all
  end

  def new
    @banner = Banner.new
    @form = BannerForm.new(@banner)
  end

  def create
    @banner = Banner.new
    @form = BannerForm.new(@banner)

    if @form.validate(params[:banner])
      @form.save
      redirect_to banners_path
    else
      render :new
    end
  end

  def edit
    @banner = Banner.find(params[:id])
    @form = BannerForm.new(@banner)
  end

  def update
    @banner = Banner.find(params[:id])
    @form = BannerForm.new(@banner)

    if @form.validate(params[:banner])
      @form.save
      redirect_to banners_path
    else
      render :edit
    end
  end

  def destroy
    @banner = Banner.find(params[:id])
    @banner.destroy
    
    redirect_to banners_path
  end

end

app/controllers/web/welcome_controller.rb
class Web::WelcomeController < Web::ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def render_source(args={})
    @html_encoder ||= HTMLEntities.new
    raw(@html_encoder.encode(render(args)))
  end
end

app/views/layouts/web/application.html.haml
!!!
%html
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=edge")
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    %title= t('.title')
    = include_gon
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      %h1= t('.title')
      = render 'layouts/web/shared/main_menu'

      = yield

    = javascript_include_tag "#{configus.faye_url}/client.js"
    = javascript_include_tag 'application', 'data-turbolinks-track' => true

app/views/layouts/web/shared/_main_menu.html.haml
%nav.navbar.navbar-default
  .container
    %ul.nav.navbar-nav
      %li= link_to t('.home'), root_path
      %li= link_to t('.banners'), banners_path
      %li= link_to t('.new_banner'), new_banner_path

app/views/web/banners/_form.html.haml
= simple_form_for @form do |f|
  = f.input :title
  = f.input :url
  = f.input :image

  = f.submit "submit", class: "btn btn-default"

app/views/web/banners/edit.html.haml
%h2= t('.title')

= render 'form'

app/views/web/banners/index.html.haml
%ul.media-list
  - @banners.each do |banner|
    %li.media(id="banner_#{banner.id}")
      .pull-left= image_tag(banner.image.url, class: 'media-object')
      .media-body
        %h4.media-heading= banner.title
        %p= link_to banner.url, banner.url
        %dl
          %dt= t('.showing')
          %dd
            %span.js-show_count= banner.show_count

          %dt= t('.clicking')
          %dd
            %span.js-click_count= banner.click_count

          %dt
            %span.js-conversion= t('.conversion')
          %dd= banner.conversion
        %p
          = link_to t('.edit'), edit_banner_path(banner), class: 'btn btn-default'
          = link_to t('.destroy'), banner_path(banner), method: :delete, data: { confirm: t('.destroy_confirmation') }, class: 'btn btn-danger'

app/views/web/banners/new.html.haml
%h2= t('.title')

= render 'form'

app/views/web/welcome/_embed_code.html.haml
#banners
:javascript
  function bannersCallback(data) {
    var text = '';
    text += '<img src="' + data.image_url + '"/>'
    text += '<a href="' + data.url +  '" target="blank">'+  data.title +'</a>'
    document.getElementById('banners').innerHTML = text;
  }
%script(src="/api/v1/random_banners.json?callback=bannersCallback")

app/views/web/welcome/index.html.haml
%p= t('.for_use')

%pre
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  = render_source 'embed_code'

%h2= t('.example')

= render 'embed_code'